server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /api

spring:
  config:
    import:
      - classpath:env.yml

  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 1000
      cache-null-values: true

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    consumer:
      group-id: gitrank
      enable-auto-commit: false
      auto-offset-reset: earliest
    retry:
      topic:
        enabled: false
        attempts: 0

  redis:
    host: localhost
    port: 6379

  flyway:
    enabled: false
  sql:
    init:
      mode: never

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

kafka-timeout: 15000
