server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  main:
    allow-bean-definition-overriding: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: true

  redis:
    host: gitrank-redis
    port: 6379

  kafka:
    bootstrap-servers: gitrank-kafka:9092
    consumer:
      group-id: gitrank
      enable-auto-commit: false
    listener:
      ack-mode: manual

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET}
            redirectUri: ${REDIRECT_URI}
            scope: repo, user, read:org
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus

blockchain:
  private-key: ${BLOCKCHAIN_PRIVATE_KEY}
  byte-code: ${BLOCKCHAIN_BYTE_CODE}
  password: ${BLOCKCHAIN_PASSWORD}
  wallet-key: ${BLOCKCHAIN_WALLET_KEY}
  contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS}
  abi: ${BLOCKCHAIN_ABI}
  keyring: ${BLOCKCHAIN_KEYING}
  smart-contract:  ${BLOCKCHAIN_CONTRACT_ADDRESS}

github:
  url: https://api.github.com/
  version-key: X-GitHub-Api-Version
  version-value: 2022-11-28

app:
  auth:
    token:
      auth-header: Authorization
      access-header: Access
      refresh-header: Refresh
      secret-key: ${JWT_SECRET_KEY}
      refresh-cookie-key: Refresh
  oauth2:
    authorizedRedirectUri: gitrank://github-auth

admin: ${ADMIN}
kafka-timeout: 15000
admin-tokens: ${ADMIN_TOKENS}
