server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gitrank-db:3306/gitrank?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  config:
    import:
      - classpath:env.yml

  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true

  cache:
    type: redis
    redis:
      time-to-live: 10800000 # 3시간
      cache-null-values: true

  redis:
    host: gitrank-redis
    port: 6379

  kafka:
    bootstrap-servers: gitrank-kafka:9092
    consumer:
      group-id: gitrank
      auto-offset-reset: earliest
      enable-auto-commit: false

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: prometheus

kafka-timeout: 15000
