apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        env:
        - name: SLACK_API_URL
          valueFrom:
            secretKeyRef:
              name: gitrank-secret
              key: slack-api-url
        command: ["/bin/sh"]
        args: ["-c", "envsubst < /etc/alertmanager/config_template.yml > /etc/alertmanager/config.yml && /bin/alertmanager"]
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
